# Copyright (C) 2020-2026 Simon Josefsson
#
# This file is part of GNU Libidn.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

variables:
  GIT_DEPTH: 100 # must include last release tag for git describe
  GNULIB_URL: https://gitlab.com/libidn/gnulib-mirror.git

stages:
 - build # B-* jobs build from git for "make dist"
 - repro # R-* jobs do "make release" from git, S-* jobs build from *-src.tar.gz
 - test # tarball test builds

default:
  interruptible: true
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - ./**/config.status
    - ./**/config.h
    - ./**/*.log
    - ./out/$CI_JOB_NAME_SLUG/**

.gnulib-fetch:
  script:
  - GNULIB_REVISION=$(. bootstrap.conf >&2; echo $GNULIB_REVISION)
  - wget -nv https://gitlab.com/libidn/gnulib-mirror/-/archive/$GNULIB_REVISION/gnulib-mirror-$GNULIB_REVISION.tar.gz
  - gzip -cd gnulib-mirror-$GNULIB_REVISION.tar.gz | tar xf -
  - rm -fv gnulib-mirror-$GNULIB_REVISION.tar.gz
  - export GNULIB_SRCDIR=$PWD/gnulib-mirror-$GNULIB_REVISION

.save-artifacts:
  script:
  - (! command -v git > /dev/null) || git status
  - (! command -v git > /dev/null) || git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,log}
  - find . -name out -prune -o -name '*.log' -print | xargs mv --backup=numbered -v -t out/$CI_JOB_NAME_SLUG/log config.h
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/ || true
  - mv -v *.tar.* out/$CI_JOB_NAME_SLUG/

Q-Debian-testing:
  tags: [ saas-linux-medium-amd64 ]
  image: debian:testing-slim
  stage: build
  before_script:
  - cat /etc/os-release
  - date | tee date.log
  - set | tee set.log
  - time apt-get update
  - time apt-get install -y git wget make autoconf automake libtool autopoint gperf gengetopt indent codespell libidn-dev | tee pkgs.log | tail
  script:
  - env srcdir=tests tests/standalone.sh
  - time apt-get remove -y --purge libidn-dev | tail
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - mkdir -pv q
  - cd q
  - time ../configure --disable-doc --enable-gcc-warnings=error
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1
  - time make -j$(nproc) check VERBOSE=t V=1
  - make V=1 srcdist
  - git status
  - git diff --exit-code # nothing should change version controlled files
  - env srcdir=../tests STANDALONE_CFLAGS="-I../lib -Ilib lib/.libs/libidn.a" ../tests/standalone.sh
  - env srcdir=../tests STANDALONE_CFLAGS="-I../lib -Ilib -Wl,-rpath lib/.libs lib/.libs/libidn.so" ../tests/standalone.sh
  - sha256sum *.tar.*
  - mkdir -pv ../out/$CI_JOB_NAME_SLUG/{src,log}
  - find config.h *.log tests/*.log -exec mv -v {} ../out/$CI_JOB_NAME_SLUG/log/ \;
  - mv -v *-src.tar.* ../out/$CI_JOB_NAME_SLUG/src/

# https://docs.gitlab.com/ee/user/application_security/sast/
sast:
  stage: build
  variables:
    SAST_EXCLUDED_PATHS: gnulib
include:
  - template: Jobs/SAST.gitlab-ci.yml

# https://www.synopsys.com/blogs/software-security/integrating-coverity-scan-with-gitlab-ci/
Coverity:
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"
  - when: manual
  image: debian:testing-slim
  stage: build
  allow_failure: true
  before_script:
  - time apt-get update -y
  - time apt-get install -y curl git wget make autoconf automake libtool autopoint gperf gengetopt codespell | tee pkgs.log | tail
  script:
  - test -n "$COVERITY_SCAN_TOKEN" && test -n "$COVERITY_SCAN_PROJECT_NAME"
  - curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64
    --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN
  - sha1sum /tmp/cov-analysis-linux64.tgz
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error --disable-doc CFLAGS="-g -Og"
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make -j$(nproc) check
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME
    --form token=$COVERITY_SCAN_TOKEN --form email=$GITLAB_USER_EMAIL
    --form file=@cov-int.tar.gz --form version="`git describe --tags`"
    --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID"
  artifacts:
    expire_in: 1 week
    paths:
      - cov-int/*.txt

.almarocky: &almarocky
  stage: build
  tags: [ saas-linux-medium-amd64 ]
  variables:
    PKGS: patch diffutils autoconf automake libtool gettext-devel git wget perl make gperf gengetopt graphviz texinfo help2man gtk-doc valgrind mono-core
  before_script:
  - cat /etc/os-release
  - time dnf install -y epel-release
  - time dnf --enablerepo=$(dnf repolist --all | grep crb > /dev/null && echo crb || echo powertools) install -y ${PKGS}
  - cc --version
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - sed -i -e '/MAKEFLAGS) dvi/d' Makefile.in # AM_DISTCHECK_DVI_TARGET=
  - time ./configure --enable-gcc-warnings=error
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - time make -j$(nproc) V=1 VERBOSE=t distcheck
  - !reference [.save-artifacts, script]

B-AlmaLinux8:
  image: almalinux:8
  extends: .almarocky

B-RockyLinux8:
  image: rockylinux:8
  extends: .almarocky

B-AlmaLinux9:
  image: almalinux:9
  extends: .almarocky

B-RockyLinux9:
  image: rockylinux:9
  extends: .almarocky

B-AlmaLinux10:
  stage: build
  tags: [ saas-linux-medium-amd64 ]
  image: almalinux:10-kitten
  variables:
    PKGS: patch diffutils autoconf automake libtool gettext-devel git wget perl make gperf graphviz valgrind dotnet-sdk-9.0
    CRBPKGS: texinfo help2man gtk-doc
    EPELPKGS: gengetopt
  before_script:
  - cat /etc/os-release
  - time dnf install -y ${PKGS}
  - time dnf --enablerepo=crb install -y ${CRBPKGS}
  - time dnf install -y epel-release
  - time dnf install -y ${EPELPKGS}
  - cc --version
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error
  - grep '^HAVE_DOTNET = 1$' Makefile > /dev/null
  - grep '^HAVE_MONO = $' Makefile > /dev/null
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - time make -j$(nproc) V=1 VERBOSE=t distcheck AM_DISTCHECK_DVI_TARGET=
  - !reference [.save-artifacts, script]

.pureosdebian: &pureosdebian
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -qqy --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless patch
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error --enable-valgrind-tests
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - make -C doc compare-makefile
  - time make -j$(nproc) V=1 VERBOSE=t distcheck AM_DISTCHECK_DVI_TARGET=
  - !reference [.save-artifacts, script]

B-PureOS10:
  image: pureos/byzantium:latest
  extends: .pureosdebian

B-Debian11:
  image: debian:11-slim
  extends: .pureosdebian

B-Devuan5:
  image: devuan/devuan:daedalus
  extends: .pureosdebian

B-Debian12:
  image: debian:12-slim
  extends: .pureosdebian

B-Trisquel11:
  image: kpengboy/trisquel:11.0
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell libidn-dev
  script:
  - env srcdir=tests tests/standalone.sh
  - time apt-get remove -y --purge libidn-dev | tail
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error --enable-valgrind-tests
  - grep '^HAVE_DOTNET = $' Makefile > /dev/null
  - grep '^HAVE_MONO = 1$' Makefile > /dev/null
  - time make syntax-check
  - time make -j$(nproc) V=1 VERBOSE=t check
  - make -C doc compare-makefile
  - time make -j$(nproc) V=1 VERBOSE=t distcheck AM_DISTCHECK_DVI_TARGET=
  - env STANDALONE_CFLAGS="-Ilib lib/.libs/libidn.a" tests/standalone.sh
  - env STANDALONE_CFLAGS="-Ilib -Wl,-rpath lib/.libs lib/.libs/libidn.so" tests/standalone.sh
  - make dist
  - !reference [.save-artifacts, script]

B-Ubuntu2204:
  image: ubuntu:22.04
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -qqy --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools dblatex valgrind gengetopt graphviz dotnet8 gperf default-jdk-headless patch codespell datefudge libidn-dev
  script:
  - env srcdir=tests tests/standalone.sh
  - time apt-get remove -y --purge libidn-dev | tail
  - !reference [.gnulib-fetch, script]
  - time datefudge "15 years" ./bootstrap --skip-po --no-git
  - mkdir b
  - cd b
  - time datefudge "15 years" ../configure --enable-gcc-warnings=error --enable-valgrind-tests
  - grep '^HAVE_DOTNET = 1$' Makefile > /dev/null
  - grep '^HAVE_MONO = $' Makefile > /dev/null
  - time datefudge "15 years" make syntax-check exclude_file_name_regexp--sc_copyright_check='version-etc.c|doc/libidn.texi'
  - time datefudge "15 years" make -j$(nproc) V=1 VERBOSE=t check
  - time datefudge "15 years" make -j$(nproc) V=1 VERBOSE=t distcheck AM_DISTCHECK_DVI_TARGET=
  - time datefudge "15 years" make -C doc compare-makefile
  - time make -j$(nproc) V=1 VERBOSE=t distcheck AM_DISTCHECK_DVI_TARGET=
  - env srcdir=../tests STANDALONE_CFLAGS="-I../lib -Ilib lib/.libs/libidn.a" ../tests/standalone.sh
  - env srcdir=../tests STANDALONE_CFLAGS="-I../lib -Ilib -Wl,-rpath lib/.libs lib/.libs/libidn.so" ../tests/standalone.sh
  - make dist
  - sha256sum *.tar.*
  - mkdir -pv ../out/$CI_JOB_NAME_SLUG/{src,log}
  - find config.h *.log tests/*.log -exec mv -v {} ../out/$CI_JOB_NAME_SLUG/log/ \;
  - mv -v *-src.tar.* ../out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ../out/$CI_JOB_NAME_SLUG/

B-Ubuntu2404-arm64:
  image: ubuntu:24.04
  tags: [ saas-linux-small-arm64 ]
  stage: build
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -qqy --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz dotnet8 gperf default-jdk-headless patch codespell indent | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error
  - grep '^HAVE_DOTNET = 1$' Makefile > /dev/null
  - grep '^HAVE_MONO = $' Makefile > /dev/null
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) distcheck AM_DISTCHECK_DVI_TARGET=
  - !reference [.save-artifacts, script]

B-Ubuntu2404:
  image: ubuntu:24.04
  tags: [ saas-linux-medium-amd64 ]
  stage: build
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -qqy --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz dotnet8 gperf default-jdk-headless patch codespell | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error --disable-silent-rules
  - grep '^HAVE_DOTNET = 1$' Makefile > /dev/null
  - grep '^HAVE_MONO = $' Makefile > /dev/null
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) distcheck AM_DISTCHECK_DVI_TARGET=
  - !reference [.save-artifacts, script]

B-Alpine-arm64:
  image: alpine:latest
  tags: [ saas-linux-small-arm64 ]
  stage: build
  before_script:
  - cat /etc/os-release
  - apk update
  - apk add gcc make libc-dev git wget autoconf automake libtool gettext-dev gperf gengetopt patch coreutils
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --disable-doc --enable-gcc-warnings=error
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1
  - time make -j$(nproc) check V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-Alpine-mold:
  image: alpine:latest
  tags: [ saas-linux-small-arm64 ]
  stage: build
  before_script:
  - cat /etc/os-release
  - apk update
  - apk add gcc make libc-dev git wget autoconf automake libtool gettext-dev gperf gengetopt patch coreutils mold
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --disable-doc --enable-gcc-warnings=error CC='cc -fuse-ld=mold'
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) V=1
  - time make -j$(nproc) check V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files
  - (! grep -E 'mold. warning' build.log)
  - grep 'mold ' lib/.libs/libidn.so

B-Debian9:
  image: docker.io/debian/eol:stretch-slim
  stage: build
  before_script:
  - printf "deb http://archive.debian.org/debian/ stretch main\ndeb http://archive.debian.org/debian/ stretch-backports main\ndeb http://archive.debian.org/debian-security/ stretch/updates main\n" > /etc/apt/sources.list # https://github.com/debuerreotype/docker-debian-eol-artifacts/issues/10
  - time apt-get update -y
  - time apt-get install -y make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist
  - time make -j$(nproc) syntax-check
  - !reference [.save-artifacts, script]

B-Debian-testing:
  image: debian:testing-slim
  stage: build
  before_script:
  - time apt-get update -qq
  - time apt-get install -y -q make git wget autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) distcheck V=1 VERBOSE=t
  - make -j$(nproc) install
  - time apt-get install -y -qq man
  - git clone --depth=1 https://salsa.debian.org/debian/libidn.git debian-libidn
  - debian-libidn/debian/tests/idn
  - debian-libidn/debian/tests/libidn
  - !reference [.save-artifacts, script]

B-Fedora-latest:
  image: fedora:latest
  stage: build
  before_script:
  - cat /etc/os-release
  - time dnf update -y
  - time dnf install -y make git wget patch autoconf automake libtool gettext-devel glibc-gconv-extra cvs texinfo texinfo-tex texlive help2man gtk-doc gengetopt dblatex valgrind gperf java-latest-openjdk-devel mono-devel codespell graphviz | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) distcheck V=1 VERBOSE=t
  - !reference [.save-artifacts, script]

B-Guix:
  rules:
  - when: always # used by merge request jobs with 'needs' on this job
  image: registry.gitlab.com/debdistutils/guix/container:extra
  stage: build
  before_script:
  - cp -rL /gnu/store/*profile/etc/* /etc/
  - echo 'root:x:0:0:root:/:/bin/sh' >> /etc/passwd
  - groupadd --system guixbuild
  - for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
  - export HOME=/
  - env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
  - guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
  - guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
  - guix describe
  - time guix install --verbosity=0 mono graphviz ghostscript
  - GUIX_PROFILE="//.guix-profile"
  - . "$GUIX_PROFILE/etc/profile"
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make V=1 dist
  - !reference [.save-artifacts, script]

# https://docs.gitlab.com/ci/runners/hosted_runners/macos/
B-macOS14Xcode15:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_MACOS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  stage: build
  image: macos-14-xcode-15
  tags: [ saas-macos-medium-m1 ]
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    WERROR_CFLAGS: "-Wno-error=format-nonliteral -Wno-error=format-security"
  before_script:
  - brew install wget autoconf automake libtool gengetopt help2man texinfo graphviz coreutils
  script:
  - PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"; export PATH
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error
  - make -j$(nproc) syntax-check
  - make -j$(nproc) check -k V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-macOS15Xcode16:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_MACOS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  stage: build
  image: macos-15-xcode-16
  tags: [ saas-macos-large-m2pro ]
  variables:
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    WERROR_CFLAGS: "-Wno-error=format-nonliteral -Wno-error=format-security"
  before_script:
  - brew install wget autoconf automake libtool gengetopt help2man texinfo graphviz coreutils
  script:
  - PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"; export PATH
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error
  - make -j$(nproc) syntax-check
  - make -j$(nproc) check -k V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-Ubuntu-rolling:
  image: ubuntu:rolling
  stage: build
  before_script:
  - cat /etc/os-release
  - time apt-get update
  - time apt-get install -y make git wget autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) distcheck V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/src out/$CI_JOB_NAME_SLUG/log
  - find config.h *.log tests/*.log -exec mv -v {} out/$CI_JOB_NAME_SLUG/log \;
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* out/$CI_JOB_NAME_SLUG/

B-clang:
  image: silkeh/clang:latest
  stage: build
  before_script:
  - cat /etc/os-release
  - clang --version
  - time apt-get update -q
  - time apt-get install -y -q --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs help2man gengetopt gperf
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error CC="clang -std=gnu2x" --disable-doc
  - time make -k syntax-check
  - time make V=1 VERBOSE=t check clean
  - time ./configure --enable-gcc-warnings=error CC="clang -std=c23"

B-gcc:
  image: gcc:latest
  stage: build
  before_script:
  - cat /etc/os-release
  - gcc --version
  - time apt-get update -q
  - time apt-get install  -y -q --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs help2man valgrind gengetopt gperf
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error CC="gcc -std=gnu2x" --disable-doc
  - time make -k syntax-check
  - time make V=1 VERBOSE=t check clean
  - time ./configure --enable-gcc-warnings CC="gcc -std=c23"

# https://docs.gitlab.com/ci/runners/hosted_runners/windows/
B-Windows-UCRT64:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_WINDOWS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: build
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=format-nonliteral -Wno-error=format-security -Wno-error=suggest-attribute=format"
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'UCRT64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu git wget autoconf automake libtool make mingw-w64-ucrt-x86_64-gcc python gtk-doc help2man gengetopt gperf patch gettext-devel
    # https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
    file configure.ac
    git config --global core.autocrlf false
    git config --global core.eol lf
    git rm -rf --cached . | tail
    git reset --hard HEAD
    git status
    git describe
    GNULIB_REVISION=$(. bootstrap.conf >&2; echo $GNULIB_REVISION)
    wget -nv https://gitlab.com/libidn/gnulib-mirror/-/archive/$GNULIB_REVISION/gnulib-mirror-$GNULIB_REVISION.tar.gz
    tar xfa gnulib-mirror-$GNULIB_REVISION.tar.gz
    rm -fv gnulib-mirror-$GNULIB_REVISION.tar.gz
    export GNULIB_SRCDIR=gnulib-mirror-$GNULIB_REVISION
    ./bootstrap --skip-po --no-git
    ./configure --enable-gcc-warnings=error --disable-doc
    git status
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep PACKAGE_VERSION config.h | grep -v modified'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS tests/tst_idna.log'

0-compare:
  image: alpine:latest
  stage: repro
  needs: [ Q-Debian-testing, B-AlmaLinux8, B-AlmaLinux9, B-RockyLinux8, B-RockyLinux9, B-Trisquel11, B-Ubuntu2204, B-PureOS10, B-Debian11, B-Debian9, B-Debian12, B-Devuan5, B-Debian-testing, B-Guix, B-Fedora-latest, B-Ubuntu-rolling, B-Ubuntu2404-arm64, B-Ubuntu2404, R-Guix, R-Debian12, R-Ubuntu2404, S-Trisquel10, S-Ubuntu2004, T-Trisquel10, T-Ubuntu2004 ]
  script:
  - cd out
  - sha256sum */*.tar.* */*/*.tar.* | sort | grep    -- -src.tar.
  - sha256sum */*.tar.* */*/*.tar.* | sort | grep -v -- -src.tar.
  - sha256sum */*.tar.* */*/*.tar.* | sort | uniq -c -w64 | sort -rn
  - sha256sum */*.tar.* */*/*.tar.* | grep    -- -src.tar. | sort | uniq -c -w64 | grep -v '^      1 '
  - sha256sum */*.tar.* */*/*.tar.* | grep -v -- -src.tar. | sort | uniq -c -w64 | grep -v '^      1 '
# Confirm modern git-archive tarball reproducibility
  - cmp b-almalinux8/src/*.tar.gz b-almalinux9/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-debian-testing/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-debian12/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-devuan5/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-rockylinux8/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-rockylinux9/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-ubuntu-rolling/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz b-ubuntu2404-arm64/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz r-debian12/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz r-guix/src/*.tar.gz
  - cmp b-almalinux8/src/*.tar.gz r-ubuntu2404/src/*v1.*.tar.gz
# Confirm old git-archive (export-subst but long git describe) tarball reproducibility
  - cmp b-trisquel11/src/*.tar.gz b-ubuntu2204/src/*.tar.gz
# Confirm really old git-archive (no export-subst) tarball reproducibility
  - cmp b-debian11/src/*.tar.gz b-debian9/src/*.tar.gz
  - cmp b-debian11/src/*.tar.gz b-pureos10/src/*.tar.gz
# Confirm 'make dist' generated tarball reproducibility
  - cmp b-almalinux8/*.tar.gz b-rockylinux8/*.tar.gz || true # flaky
  - cmp b-almalinux9/*.tar.gz b-rockylinux9/*.tar.gz
  - cmp b-devuan5/*.tar.gz b-debian12/*.tar.gz
  - cmp b-guix/*.tar.gz r-guix/*.tar.gz
  - cmp b-pureos10/*.tar.gz b-debian11/*.tar.gz
  - cmp b-trisquel11/*.tar.gz b-ubuntu2204/*.tar.gz
  - cmp b-ubuntu2404-arm64/*.tar.gz b-ubuntu2404/*.tar.gz
  - cmp t-trisquel10/*.tar.gz t-ubuntu2004/*.tar.gz
# Confirm 'make dist' from git-archive tarball reproducibility
  - cmp s-trisquel10/*.tar.gz s-ubuntu2004/*.tar.gz
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - ./out/**

R-Guix:
  tags: [ saas-linux-medium-amd64 ]
  image: registry.gitlab.com/debdistutils/guix/container:extra
  stage: repro
  needs: []
  before_script:
  - cp -rL /gnu/store/*profile/etc/* /etc/
  - echo 'root:x:0:0:root:/:/bin/sh' > /etc/passwd
  - echo 'root:x:0:' > /etc/group
  - groupadd --system guixbuild
  - for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
  - export HOME=/
  - env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
  - guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
  - guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
  - guix describe
  - time guix install --verbosity=0 mono graphviz ghostscript
  - GUIX_PROFILE="//.guix-profile"
  - . "$GUIX_PROFILE/etc/profile"
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --no-git
  - time ./configure
  - time make V=1 syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist V=1 VERBOSE=t
  - git status
  - git diff --exit-code
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout -B cibranch
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      sed -i -e 's,STRINGPREP_VERSION ".*",STRINGPREP_VERSION "97.23.42",' lib/stringprep.h
      git commit -m "Warn about automatic release." NEWS lib/stringprep.h
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t AM_DISTCHECK_DVI_TARGET=
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find config.h *.log tests/*.log -exec mv -v {} out/$CI_JOB_NAME_SLUG/log \;
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

R-Debian12:
  tags: [ saas-linux-medium-amd64 ]
  image: debian:12-slim
  stage: repro
  needs: []
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time apt-get update
  - time eatmydata apt-get install -y -q make git wget autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless wget
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error
  - time make syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist V=1 VERBOSE=t
  - sha256sum *.tar.*
  - git status
  - git diff --exit-code
  - time apt-get install -y -q --no-install-recommends gpg gpgv2 gpg-agent
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout -B cibranch
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      sed -i -e 's,STRINGPREP_VERSION ".*",STRINGPREP_VERSION "97.23.42",' lib/stringprep.h
      git commit -m "Warn about automatic release." NEWS lib/stringprep.h
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find config.h *.log tests/*.log -exec mv -v {} out/$CI_JOB_NAME_SLUG/log \;
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

R-Ubuntu2404:
  image: ubuntu:24.04
  tags: [ saas-linux-medium-amd64 ]
  stage: repro
  needs: []
  before_script:
  - cat /etc/os-release
  - time apt-get update -q
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -qqy --no-install-recommends make git wget autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz ghostscript dotnet8 gperf default-jdk-headless patch codespell indent
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings
  - time make -j$(nproc) syntax-check
  - time make -j$(nproc) check V=1 VERBOSE=t
  - time make -j$(nproc) dist
  - sha256sum *.tar.*
  - git status
  - git diff --exit-code # nothing should change version controlled files
  - apt-get install -y -q gpg gpgv
  - gpg --batch --passphrase '' --quick-gen-key pipeline@example.org
  - git checkout $CI_COMMIT_BRANCH
  - git config user.email "pipeline@example.org"
  - git config user.name "Pipeline Builder"
  - git config user.signingkey pipeline@example.org
  - |
    if test -z "$CI_COMMIT_TAG"; then
      sed -i '3i * Noteworthy changes in release ?.? (????-??-??) [?]\n\n** WARNING This release was prepared automatically with no testing.\n' NEWS
      sed -i -e 's,STRINGPREP_VERSION ".*",STRINGPREP_VERSION "97.23.42",' lib/stringprep.h
      git commit -m "Warn about automatic release." NEWS lib/stringprep.h
      relver='97.23.42'
      reltyp='alpha'
    else # maintainer ran release-commit
      relver=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\1/p' | head -1)
      reltyp=$(cat NEWS | sed -n -e 's/.*release \([0-9.]\+\) (....-..-..) \[\(.*\)\].*/\2/p' | head -1)
    fi
  - test "$relver" != "97.23.42" || make release-commit RELEASE="$relver $reltyp"
  - make release RELEASE="$relver $reltyp" V=1 VERBOSE=t
  - cat -n ~/announce-*
  - git diff --exit-code # nothing should change version controlled files
  - sha256sum *.tar.*
  - mkdir -pv out/$CI_JOB_NAME_SLUG/{src,rel,log}
  - find config.h *.log tests/*.log -exec mv -v {} out/$CI_JOB_NAME_SLUG/log \;
  - test "$relver" != "97.23.42" || mv -v *97.23.42* out/$CI_JOB_NAME_SLUG/rel/
  - mv -v *-src.tar.* out/$CI_JOB_NAME_SLUG/src/
  - mv -v *.tar.* ~/announce-* out/$CI_JOB_NAME_SLUG/

T-Trisquel10:
  tags: [ saas-linux-medium-amd64 ]
  image: docker.io/kpengboy/trisquel:10.0
  stage: repro
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -q -y --no-install-recommends make git wget ca-certificates autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz ghostscript mono-mcs gperf default-jdk-headless codespell datefudge patch
  script:
  - mkdir -pv ../b
  - cd ../b
  - tar xfz ../libidn/out/b-guix/src/libidn-*.tar.gz
  - cd $(tar tfa ../libidn/out/b-guix/src/libidn-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time datefudge "5 years" ./bootstrap --skip-po --no-git
  - time datefudge "5 years" ./configure --enable-gcc-warnings=error
  - grep '^HAVE_DOTNET = $' Makefile > /dev/null
  - grep '^HAVE_MONO = 1$' Makefile > /dev/null
  - time datefudge "5 years" make -j$(nproc) syntax-check exclude_file_name_regexp--sc_copyright_check='version-etc.c|doc/libidn.texi'
  - time datefudge "5 years" make -j$(nproc) check V=1 VERBOSE=t
  - time datefudge "5 years" make -j$(nproc) distcheck
  - sha256sum *.tar.*
  - mkdir -pv ../../libidn/out/$CI_JOB_NAME_SLUG/src ../../libidn/out/$CI_JOB_NAME_SLUG/log
  - find config.h *.log tests/*.log -exec mv -v {} ../out/$CI_JOB_NAME_SLUG/log \;
  - mv -v *.tar.* ../../libidn/out/$CI_JOB_NAME_SLUG/

T-Ubuntu2004:
  tags: [ saas-linux-medium-amd64 ]
  image: ubuntu:20.04
  stage: repro
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -y --no-install-recommends make git wget ca-certificates autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz ghostscript mono-mcs gperf default-jdk-headless codespell datefudge patch | tee pkgs.log | tail
  script:
  - tar xfz out/b-guix/src/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/src/libidn-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time datefudge "5 years ago" ./bootstrap --skip-po --no-git
  - time datefudge "5 years ago" ./configure --enable-gcc-warnings=error
  - grep '^HAVE_DOTNET = $' Makefile > /dev/null
  - grep '^HAVE_MONO = 1$' Makefile > /dev/null
  - time datefudge "5 years ago" make -j$(nproc) syntax-check exclude_file_name_regexp--sc_copyright_check='version-etc.c|doc/libidn.texi'
  - time datefudge "5 years ago" make -j$(nproc) check V=1 VERBOSE=t
  - time datefudge "5 years ago" make -j$(nproc) distcheck V=1 VERBOSE=t
  - sha256sum *.tar.*
  - mkdir -pv ../out/$CI_JOB_NAME_SLUG/log
  - find config.h *.log tests/*.log -exec mv -v {} ../out/$CI_JOB_NAME_SLUG/log \;
  - mv -v *.tar.* ../out/$CI_JOB_NAME_SLUG/

S-Trisquel10:
  tags: [ saas-linux-medium-amd64 ]
  image: docker.io/kpengboy/trisquel:10.0
  stage: repro
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -y
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell
  script:
  - mkdir -pv ../b
  - cd ../b
  - tar xfz ../*/out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa ../*/out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --no-git
  - time ./configure --enable-gcc-warnings=error
  - grep '^VERSION = ' Makefile | grep -v UNKNOWN
  - time make -j$(nproc) check V=1 VERBOSE=t
  - src/idn --version | head -1 | grep -v UNKNOWN
  - time make -j$(nproc) dist AM_DISTCHECK_DVI_TARGET=
  - sha256sum *.tar.*
  - mkdir -pv $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/{src,log}
  - find config.h *.log tests/*.log -exec mv -v {} $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/log \;
  - mv -v *.tar.* $CI_PROJECT_DIR/out/$CI_JOB_NAME_SLUG/

S-Ubuntu2004:
  tags: [ saas-linux-medium-amd64 ]
  image: ubuntu:20.04
  stage: repro
  needs: [B-Guix]
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
  - cat /etc/os-release
  - sed -i 's,http://archive.trisquel.info/trisquel,http://ftp.acc.umu.se/mirror/trisquel/packages,' /etc/apt/sources.list
  - time apt-get update -y
  - time apt-get install -y -q eatmydata
  - time eatmydata apt-get install -y make git wget autoconf automake libtool gettext autopoint cvs texinfo help2man gtk-doc-tools valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell
  script:
  - tar xfz out/b-guix/src/*-*.tar.gz
  - cd $(tar tfa out/b-guix/src/*-*.tar.gz | head -n1)
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --no-git
  - time ./configure --enable-gcc-warnings=error
  - grep '^VERSION = ' Makefile | grep -v UNKNOWN
  - time make -j$(nproc) check V=1 VERBOSE=t
  - src/idn --version | head -1 | grep -v UNKNOWN
  - time make -j$(nproc) dist AM_DISTCHECK_DVI_TARGET=
  - sha256sum *.tar.*
  - mkdir -pv ../out/$CI_JOB_NAME_SLUG/{src,log}
  - find config.h *.log tests/*.log -exec mv -v {} ../out/$CI_JOB_NAME_SLUG/log \;
  - mv -v *.tar.* ../out/$CI_JOB_NAME_SLUG/

AlmaLinux8:
  image: almalinux:8
  stage: test
  needs: [B-Guix]
  before_script:
  - time dnf -y install make gcc diffutils valgrind | tee pkgs.log | tail
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

AlmaLinux10:
  image: almalinux:10-kitten
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make gcc diffutils valgrind gzip
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

AlmaLinux10-clang:
  image: almalinux:10-kitten
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make clang diffutils valgrind gzip
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure CC=clang --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

AlmaLinux10-arm64:
  image: almalinux:10-kitten
  tags: [ saas-linux-small-arm64 ]
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make gcc diffutils valgrind gzip
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

AlmaLinux10-ppc64:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_PPC64_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ ppc64 ]
  image: almalinux:10-kitten
  stage: test
  needs: [B-Guix]
  before_script:
  - dnf -y install make gcc diffutils valgrind gzip
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Alpine-mold:
  image: alpine:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - apk update
  - apk add build-base mold
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=format-nonliteral"
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error CC='cc -fuse-ld=mold'
  - make -j$(nproc) check V=1 VERBOSE=t 2>&1 | tee build.log
  - (! grep -E 'mold. warning' build.log)
  - grep 'mold ' lib/.libs/libidn.so

ArchLinux:
  image: archlinux:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - pacman -Syu --noconfirm make gcc diffutils
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Armcross:
  image: debian:12-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - time apt-get update -qq
  - time apt-get install -y -qq make gcc-arm-linux-gnueabi qemu-user qemu-user-binfmt file binfmt-support | tee pkgs.log | tail
  - update-binfmts --enable qemu-arm
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings=error --host=arm-linux-gnueabi CFLAGS="-static --static"
  - make -j$(nproc) V=1
  - file src/idn
  - LANG=C.UTF-8 qemu-arm src/idn --debug foo
  - time make -k -j$(nproc) check V=1 VERBOSE=t

OracleLinux7:
  image: oraclelinux:7
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - yum -y install make gcc diffutils valgrind
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Debian3.1:
  image: debian/eol:sarge
  stage: test
  needs: [B-Guix]
  before_script:
  - time apt-get update
  - time apt-get install -y -qq make gcc libc-dev
  script:
  - tar xfz out/b-guix/libidn-*.tar.gz
  - cd $(tar tfz out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make check V=1 VERBOSE=t

Debian4:
  image: debian/eol:etch
  stage: test
  needs: [B-Guix]
  before_script:
  - time apt-get update
  - time apt-get install -y -qq make gcc libc-dev
  script:
  - tar xfz out/b-guix/libidn-*.tar.gz
  - cd $(tar tfz out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make check V=1 VERBOSE=t

Debian10:
  image: debian/eol:buster-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - time apt-get update
  - time apt-get install -y -qq make gcc
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Debian12-ppc64:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_PPC64_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ ppc64 ]
  image: debian:12
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - time apt-get update
  - time apt-get install -y -qq make gcc
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Fedora41:
  image: fedora:41
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - dnf -y install make gcc diffutils valgrind
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Fedora-latest:
  image: fedora:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - dnf -y install make gcc diffutils valgrind awk
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Guix:
  image: registry.gitlab.com/debdistutils/guix/container:latest
  stage: test
  needs: [B-Guix]
  before_script:
  - cp -rL /gnu/store/*profile/etc/* /etc/
  - echo 'root:x:0:0:root:/:/bin/sh' >> /etc/passwd
  - groupadd --system guixbuild
  - for i in $(seq -w 1 10); do useradd -g guixbuild -G guixbuild -d /var/empty -s $(command -v nologin) -c "Guix build user $i" --system guixbuilder$i; done
  - export HOME=/
  - env LANG=C.UTF-8 guix-daemon --build-users-group=guixbuild &
  - guix archive --authorize < /share/guix/ci.guix.gnu.org.pub
  - guix archive --authorize < /share/guix/bordeaux.guix.gnu.org.pub
  - guix describe
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Mingw32:
  image: debian:12-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - dpkg --add-architecture i386
  - time apt-get update -qq
  - time apt-get install -y -qq make mingw-w64 wine wine32 libwine libwine:i386 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=format-nonliteral -Wno-error=format-security -Wno-error=suggest-attribute=format"
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings=error --host=i686-w64-mingw32 CC='i686-w64-mingw32-gcc -static-libgcc'
  - time make -k -j$(nproc) check V=1 VERBOSE=t

Mingw64:
  image: debian:12-slim
  stage: test
  needs: [B-Guix]
  before_script:
  - time apt-get update -qq
  - time apt-get install -y -qq make mingw-w64 wine wine64 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=format-nonliteral -Wno-error=format-security -Wno-error=suggest-attribute=format"
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - mkdir b
  - cd b
  - time ../configure --enable-gcc-warnings=error --host=x86_64-w64-mingw32
  - time make -k -j$(nproc) check V=1 VERBOSE=t

OpenBSD:
  tags: [ "openbsd" ]
  allow_failure: true
  needs: [B-Guix]
  stage: test
  before_script:
  - uname -a
  - sysctl hw
  script:
  - tar xfz out/b-guix/libidn-*.tar.gz
  - cd $(tar tfz out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make check V=1 VERBOSE=t

RockyLinux9-ppc64:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_PPC64_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ ppc64 ]
  image: rockylinux:9
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - dnf -y install make gcc valgrind
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Ubuntu12.04:
  image: ubuntu:12.04
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - perl -pi -e 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
  - time apt-get update -q
  - time apt-get install -y -qq make gcc valgrind
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Ubuntu14.04:
  image: ubuntu:14.04
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -y -qq make gcc valgrind
  script:
  - mkdir -pv ../p
  - cd ../p
  - tar xfa ../libidn/out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa ../libidn/out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --disable-tld --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t

Ubuntu-rolling:
  image: ubuntu:rolling
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -y -qq git make gcc valgrind gtk-doc-tools texinfo texlive texlive-plain-generic graphviz
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - make -j$(nproc) distcheck

Ubuntu-rolling-arm64:
  image: ubuntu:rolling
  tags: [ saas-linux-small-arm64 ]
  stage: test
  needs: [B-Guix]
  before_script:
  - cat /etc/os-release
  - time apt-get update -qq
  - time apt-get install -y -qq git make gcc valgrind gtk-doc-tools texinfo
  script:
  - tar xfa out/b-guix/libidn-*.tar.gz
  - cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
  - time ./configure --enable-gcc-warnings=error
  - time make -j$(nproc) check V=1 VERBOSE=t
  - (! make -j$(nproc) distcheck)
  - make -j$(nproc) distcheck AM_DISTCHECK_DVI_TARGET=

Windows-MSYS:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_WINDOWS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Guix]
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=attributes -Wno-error=format-nonliteral -Wno-error=format-security"
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MSYS' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make gcc
    tar xfa out/b-guix/libidn-*.tar.gz
    cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
    ./configure --enable-gcc-warnings=error --disable-doc
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS libidn-*/tests/tst_idna.log'

Windows-MINGW64:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_WINDOWS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  tags: [ saas-windows-medium-amd64 ]
  stage: test
  needs: [B-Guix]
  variables:
    WERROR_CFLAGS: "-Wno-error=unused-value -Wno-error=format-nonliteral -Wno-error=format-security -Wno-error=suggest-attribute=format"
  script: # https://www.msys2.org/docs/ci/#other-systems
  - wget.exe -nv --no-check-certificate -O msys2.exe https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe
  - ./msys2.exe -y -oC:\
  - Remove-Item msys2.exe
  - $env:CHERE_INVOKING = 'yes'
  - $env:MSYSTEM = 'MINGW64' # https://www.msys2.org/docs/environments/
  - C:\msys64\usr\bin\bash -lc ' '
  - C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -Syuu'
  - |
    C:\msys64\usr\bin\bash -lcx '
    pacman --noconfirm -Syu make mingw-w64-x86_64-gcc
    tar xfa out/b-guix/libidn-*.tar.gz
    cd $(tar tfa out/b-guix/libidn-*.tar.gz | head -n1)
    ./configure --enable-gcc-warnings=error --disable-doc
    make -j$(nproc) V=1 -k check VERBOSE=t'
  - C:\msys64\usr\bin\bash -lc 'grep ^PASS libidn-*/tests/tst_idna.log'

macOS15Xcode16:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $LIBIDN_CI_RUN_MACOS_JOBS
  - if: $LIBIDN_CI_MANUAL_JOBS
    when: manual
  image: macos-15-xcode-16
  tags: [ saas-macos-medium-m1 ]
  stage: test
  needs: [B-Guix]
  variables:
    WERROR_CFLAGS: "-Wno-error=format-nonliteral -Wno-error=format-security"
  script:
  - gzip -cd out/b-guix/libidn-*.tar.gz | tar xf -
  - cd $(gzip -cd out/b-guix/libidn-*.tar.gz | tar tf - | head -n1)
  - mkdir b
  - cd b
  - ../configure --enable-gcc-warnings=error
  - make -j$(nproc) syntax-check
  - make -j$(nproc) V=1 check -k VERBOSE=t

.pages:
  image: debian:testing-slim
  stage: build
  before_script:
  - time apt-get update -qq
  - time apt-get install -y -q make git wget autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt graphviz mono-mcs gperf default-jdk-headless codespell | tee pkgs.log | tail
  script:
  - !reference [.gnulib-fetch, script]
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-gcc-warnings=error --enable-java --enable-gtk-doc --enable-gtk-doc-pdf
  - time make V=1
  - mkdir -p public
  - rm -rf public/reference
  - mv doc/reference/html public/reference
  - make web-manual
  - test -f doc/manual/libidn.pdf
  - rm -rf public/manual
  - mv -v doc/manual public/manual
  artifacts:
    when: on_success
    paths:
      - public

pages:
  extends: .pages
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages-test:
  extends: .pages
  rules:
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
